### ISSUE TITLE
Crashes when using a key on an already used vault

### ISSUE THREAD

**Issue by CharlesNicholas1999** [Buuz135/Repeatable-Trial-Vaults#2]
Hi, thanks for the work you put into the mod I think its kinda dumb that you cant repeat vaults. 

I seem to crash every time I try to give a key to a vault that has been used. I have quite a few mods installed, but will find out if any are the cause of the crash soon.

Please find the crash report below ... 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-09-09 14:20:03
Description: Exception in server tick loop

java.lang.IllegalAccessError: class net.minecraft.class_9197 tried to access private field net.minecraft.class_9204.field_48888 (net.minecraft.class_9197 and net.minecraft.class_9204 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5a4aa2f2)
	at net.minecraft.class_9197.handler$bpk000$repeatable_trial_vaults$useItemOn(class_9197.java:531)
	at net.minecraft.class_9197.method_55765(class_9197.java)
	at net.minecraft.class_4970$class_4971.method_55780(class_4970.java:1169)
	at net.minecraft.class_3225.method_14262(class_3225.java:348)
	at net.minecraft.class_3244.method_12046(class_3244.java:1158)
	at net.minecraft.class_2885.method_12547(class_2885.java:42)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at net.minecraft.class_1255.method_18857(class_1255.java:145)
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 259721792 bytes (247 MiB) / 1577058304 bytes (1504 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 22.20.16.4836
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.15.3742
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 21711.88
	Virtual memory used (MiB): 19669.63
	Swap memory total (MiB): 13644.72
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 12152.66, total: 120827.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 12152.66, total: 120827.00
	Space in storage for io.netty.native.workdir (MiB): available: 12152.66, total: 120827.00
	Space in storage for java.io.tmpdir (MiB): available: 12152.66, total: 120827.00
	Space in storage for workdir (MiB): available: 12152.66, total: 120827.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bowinfinityfix: Bow Infinity Fix 3.1.0
		cherishedworlds: Cherished Worlds 10.0.0+1.21
		clickopener: Click Opener Continued! 1.0.0+1.21
		clumps: Clumps 18.0.0.1
		cobweb: Cobweb 1.1.2
		comforts: Comforts 9.0.0+1.21
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
			spectrelib: SpectreLib 0.17.1+1.21
		continuity: Continuity 3.0.0-beta.5+1.21
		controlling: Controlling 18.0.1
		craftify: Craftify 1.16.0
			elementa: Elementa 636
			universalcraft: UniversalCraft 342
			vigilance: Vigilance 295
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		harvest_with_ease: Harvest with ease 9.0.1
		iceberg: Iceberg 1.2.5
		indium: Indium 1.0.34+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.0
		itemscroller: Item Scroller 0.24.50
		itemswapper: ItemSwapper 0.7.0
		java: OpenJDK 64-Bit Server VM 21
		legendarytooltips: Legendary Tooltips 1.4.11
		libipn: libIPN 5.0.0
		litematica: Litematica 0.19.50
		lithium: Lithium 0.12.7
		malilib: MaLiLib 0.21.0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.32.50
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mr_keep_someinventory: Keep Some Inventory 1-v2.0.1
		prism: root project 'Prism' 1.0.8
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		repeatable_trial_vaults: Repeatable Trial Vaults 1.0.0
		searchables: Searchables 1.0.5
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		tweakeroo: Tweakeroo 0.21.50
		worldedit: WorldEdit 7.3.6+6892-3d660b8
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Charcat_9'/68, l='ServerLevel[Nothing]', x=-1589.34, y=15.38, z=1794.31]]
	Active Data Packs: vanilla, fabric, comforts (incompatible), fabric-convention-tags-v2, mr_keep_someinventory, repeatable_trial_vaults (incompatible), file/anti enderman grief v1.1.8 (MC 1.21-1.21.1).zip, file/anti ghast grief v1.1.8 (MC 1.21-1.21.1).zip, file/double shulker shells v1.3.8 (MC 1.21-1.21.1).zip, file/durability ping v1.1.8 (MC 1.21-1.21.1).zip, file/ender chest always drops v1.0.0 (MC 1.21-1.21.1).zip, file/fast leaf decay v2.0.11 (MC 1.21-1.21.1).zip, file/more effective tools v1.0.2 (MC 1.21-1.21.1).zip, file/unlock all recipes v2.0.9 (MC 1.21-1.21.1).zip, file/wandering trades v1.7.6 (MC 1.21-1.21.1).zip
	Available Data Packs: bundle, comforts (incompatible), fabric, fabric-convention-tags-v2, file/anti enderman grief v1.1.8 (MC 1.21-1.21.1).zip, file/anti ghast grief v1.1.8 (MC 1.21-1.21.1).zip, file/double shulker shells v1.3.8 (MC 1.21-1.21.1).zip, file/durability ping v1.1.8 (MC 1.21-1.21.1).zip, file/ender chest always drops v1.0.0 (MC 1.21-1.21.1).zip, file/fast leaf decay v2.0.11 (MC 1.21-1.21.1).zip, file/more effective tools v1.0.2 (MC 1.21-1.21.1).zip, file/unlock all recipes v2.0.9 (MC 1.21-1.21.1).zip, file/wandering trades v1.7.6 (MC 1.21-1.21.1).zip, mr_keep_someinventory, repeatable_trial_vaults (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 3968612249720917337
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.2-1.21

**Comment by Buuz135** [comment]
Update the mod
