### ISSUE TITLE
Can't suggest this to the server hosting site Aternos

### ISSUE THREAD

**Issue by DavidFerreira1002** [Buuz135/Repeatable-Trial-Vaults#3]
I want to use this mod in the Aternos server hosting site, but when I try to suggest it I get the error:

"This cant be added for technical reasons."

Stating this (from [here](https://support.aternos.org/hc/en-us/articles/360052255311-Suggesting-new-mods-plugins-and-modpacks)):

The suggestion is not compatible with Aternos. For example, if a plugin requires an additional port, has a huge negative performance impact, or changes the online player count of a server, it can't be added.

I have no clue at what could be doing this, so I decided to open a new issue for this, maybe it is not the best place for it, if so sorry about it.

**Comment by Buuz135** [comment]
I have no idea either, nothing is blocked, open a ticket with then to get more information

**Comment by DavidFerreira1002** [comment]
This was their reason:

1. all his files are listed as beta 2. It has existed for a very short time. So even if it was technically possioble, it would not fulfill a few other requirements

**Comment by Buuz135** [comment]
What a stupid reason, I changed the files to release
